DROP DATABASE IF EXISTS zk23liimafb54494;
CREATE DATABASE zk23liimafb54494;

USE zk23liimafb54494;

CREATE TABLE burgers (
  id INTEGER AUTO_INCREMENT NOT NULL,
  burger_name VARCHAR(30),
  devoured BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
);